name: Run Neuron Script

on:
  schedule:
    - cron: "0 */5 * * *"
  workflow_dispatch:

jobs:
  run-neuron:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "omotoyedave4@gmail.com"

      - name: Run script
        run: python save.py

      - name: Commit and Push results
        run: |
          git add .
          git commit -m "Trying neuron update" || echo "No changes to commit"
          git push
